version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres     # change this
      POSTGRES_PASSWORD: example  # change this
      POSTGRES_DB: mydatabase     # change this
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
